---

- name: patch and reboot linux servers
  hosts: all
  gather_facts: true
  tasks:

  - name: get host id from satellite
    uri:
      url: "{{ sat_url }}/api/v2/hosts?search={{ inventory_hostname }}"
      validate_certs: false
      method: GET
      headers:
        Content-Type: "application/json"
        Accept: "application/json,version=2"
      user: "{{ sat_user }}"
      password: "{{ sat_password }}"
      force_basic_auth: yes
      status_code: 200
    register: host_id
    delegate_to: localhost

  - name: get content view id from satellite
    uri:
      url: "{{ sat_url }}/katello/api/content_views?search={{ content_view_name }}"
      validate_certs: false
      method: GET
      headers:
        Content-Type: "application/json"
        Accept: "application/json,version=2"
      user: "{{ sat_user }}"
      password: "{{ sat_password }}"
      force_basic_auth: yes
      status_code: 200
    register: content_view_id
    delegate_to: localhost

  - name: update content view of host
    uri:
      url: "{{ sat_url }}/api/v2/hosts/{{ host_id.json.results[0].id }}"
      validate_certs: false
      method: PUT
      headers:
        Content-Type: "application/json"
        Accept: "application/json,version=2"
      body: {"host": {"content_facet_attributes": {"content_view_id": "{{ content_view_id.json.results[0].id }}"}}}
      body_format: json
      user: "{{ sat_user }}"
      password: "{{ sat_password }}"
      force_basic_auth: yes
      status_code: 200
    when: "host_id.json.results[0].content_facet_attributes.content_view_id != content_view_id.json.results[0].id"
    delegate_to: localhost

  - name: check for available updates
    command: yum check-update
      args:
        warn: false
    register: yum_updates
    failed_when: yum_updates.rc == 1
    changed_when: false

  - name: run script prior to reboot
    script: script.sh
    when: yum_updates.rc == 100

  - name: health reboot before patching
    reboot:
    when: yum_updates.rc == 100

  - name: run script
    script: script.sh
    when: yum_updates.rc == 100

  - name: yum update
    yum:
      name: "*"
      state: latest
    register: patched
    when: yum_updates.rc == 100

  - name: reboot after patching
    reboot:
    when: patched is changed

  - name: script
    script: script.sh
    when: yum_updates.rc == 100
